name: BCLD VENDORLESS RELEASE

on:
  push:
    branches:
      - main
jobs:
  vendorless-release:
    runs-on: ubuntu-22.04
    environment: release
    container:
      image: ubuntu:jammy
      options: --privileged
      env:
        BCLD_APP: ${{ vars.BCLD_APP }}
        BCLD_CFG_EDIT: ${{ vars.BCLD_CFG_EDIT }}
        BCLD_MODEL: ${{ vars.BCLD_MODEL }}
        CLEAN_BOOTSTRAP: ${{ vars.CLEAN_BOOTSTRAP }}
        NULLFIX: ${{ vars.NULLFIX }}
        POINTER_TYPE: ${{ vars.POINTER_TYPE }}
      volumes:
        - /dev:/dev:ro
        - /run:/run:rw
        - /var/docker.sock:/var/docker.sock:ro
        - ${{ github.workspace }}:/project:rw
    steps:
    - name: Checkout local repository
      uses: actions/checkout@v2
    - name: Manually downloading submodules...
      run: |
        /usr/bin/apt-get update
        /usr/bin/apt-get install -y git
        /usr/bin/mkdir -pv modules
        cd modules || exit
        /usr/bin/git clone https://github.com/bats-core/bats-core.git
        /usr/bin/git clone https://github.com/bats-core/bats-support.git
        /usr/bin/git clone https://github.com/bats-core/bats-assert.git
        /usr/bin/git clone https://github.com/jbbletterman/bcld.wiki.git
        cd - || exit
    - name: Install dependencies
      run: |
        /usr/bin/apt-get update
        /usr/bin/apt-get upgrade -y
        /usr/bin/apt-get install -y $(cat /project/config/packages/BUILD)
    - name: Run Wiki Exporter
      run: |
        /usr/bin/bash -c './tools/WIKI-exporter.sh'
    - name: Upload BCLD Wiki
      uses: actions/upload-artifact@v2
      with:
        name: BCLD WIKI
        path: /project/artifacts/bcld.wiki.zip
    - name: Run BCLD BATS
      run: |
        /usr/bin/bash -c './test/BCLD-BATS.sh'
    - name: Upload LICENSE-REPORT
      uses: actions/upload-artifact@v2
      with:
        name: LICENSE-REPORT
        path: /project/test/LICENSE-REPORT.txt

    - name: Upload SHELL-REPORT
      uses: actions/upload-artifact@v2
      with:
        name: SHELL-REPORT
        path: /project/test/SHELL-REPORT.md
    - name: Upload BATS-REPORT
      uses: actions/upload-artifact@v2
      with:
        name: BATS-REPORT
        path: /project/test/BATS-REPORT.txt
    - name: Upload kernel image
      uses: actions/upload-artifact@v2
      with:
        name: BCLD Kernel
        path: /project/artifacts/vmlinuz
    - name: Upload BCLD Ramdisk
      uses: actions/upload-artifact@v2
      with:
        name: BCLD-RAMFS
        path: /project/artifacts/initrd
    - name: Upload BCLD-ISO
      uses: actions/upload-artifact@v2
      with:
        name: BCLD-ISO
        path: /project/artifacts/bcld.iso
    - name: Upload BCLD-IMG
      uses: actions/upload-artifact@v2
      with:
        name: BCLD-IMG
        path: /project/artifacts/*.img

